import { useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

const properties = [
  { id: 1, title: "The Cedar House", location: "Hudson Valley, New York", price: "$1,285,000", type: "For sale", details: "3 beds  /  2 baths  /  1,942 sq ft", image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85", tag: "Just listed" },
  { id: 2, title: "Casa Solana", location: "Palm Springs, California", price: "$5,800 / month", type: "For rent", details: "2 beds  /  2 baths  /  1,210 sq ft", image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85", tag: "Editor's pick" },
  { id: 3, title: "Lakeside A-Frame", location: "Lake Tahoe, California", price: "$935,000", type: "For sale", details: "2 beds  /  1 bath  /  988 sq ft", image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=85", tag: "Price reduced" },
];
const navItems = ["Explore", "How it works", "Guides"];

function App() {
  const [activeType, setActiveType] = useState("Buy");
  const [query, setQuery] = useState("");
  const [saved, setSaved] = useState([]);
  const [showListing, setShowListing] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [notice, setNotice] = useState("");
  const visibleProperties = useMemo(() => {
    const normalized = query.trim().toLowerCase();
    return properties.filter((property) => (activeType === "Buy" ? property.type === "For sale" : property.type === "For rent") && (!normalized || `${property.title} ${property.location}`.toLowerCase().includes(normalized)));
  }, [activeType, query]);
  const toggleSaved = (id) => setSaved((current) => current.includes(id) ? current.filter((savedId) => savedId !== id) : [...current, id]);
  const handleSearch = (event) => { event.preventDefault(); document.getElementById("listings")?.scrollIntoView({ behavior: "smooth" }); };
  const handleListingSubmit = (event) => { event.preventDefault(); setShowListing(false); setNotice("Your listing draft is ready. We will be in touch shortly."); window.setTimeout(() => setNotice(""), 4500); };
  return <div className="app-shell">
    <header className="site-header"><a className="brand" href="#top" aria-label="Morrow home"><span className="brand-mark">M</span><span>morrow</span></a><nav className={`main-nav ${menuOpen ? "is-open" : ""}`} aria-label="Primary navigation" id="primary-navigation">{navItems.map((item, index) => <a key={item} className={index === 0 ? "active" : ""} href={index === 0 ? "#listings" : `#${item.toLowerCase().replaceAll(" ", "-")}`}>{item}</a>)}<button className="mobile-list-button" onClick={() => setShowListing(true)}>List your property</button></nav><div className="header-actions"><button className="saved-link" onClick={() => setNotice(`${saved.length} saved ${saved.length === 1 ? "home" : "homes"}`)} aria-label="View saved homes">Saved ({saved.length})</button><button className="outline-button list-button" onClick={() => setShowListing(true)}>List your property <span aria-hidden="true">+</span></button><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-controls="primary-navigation" aria-label="Toggle menu"><span></span><span></span></button></div></header>
    <main id="top">
      <section className="hero-section"><div className="hero-copy"><p className="eyebrow">A better way home</p><h1>Find a place<br /><em>worth staying for.</em></h1><p className="hero-intro">Homes with a little more soul, and a lot less noise. Browse honest listings from people who care about where you live next.</p><form className="search-panel" onSubmit={handleSearch}><div className="mode-switch" role="tablist" aria-label="Search property type">{["Buy", "Rent"].map((mode) => <button key={mode} type="button" role="tab" aria-selected={activeType === mode} className={activeType === mode ? "selected" : ""} onClick={() => setActiveType(mode)}>{mode}</button>)}</div><label className="search-input"><span className="search-icon" aria-hidden="true"></span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="City, neighborhood, or address" aria-label="Search by city, neighborhood, or address" /></label><button className="search-button" type="submit">Search <span aria-hidden="true">&#8599;</span></button></form><div className="hero-note"><span className="avatar-stack"><i></i><i></i><i></i></span><span>Trusted by 12,000+ thoughtful movers</span></div></div><div className="hero-image-wrap"><img src="https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1600&q=85" alt="Warm modern living room overlooking a garden" /><div className="image-caption"><span>01</span><span>Light-filled living, Marin County</span></div></div></section>
      <section className="category-strip" aria-label="Browse by lifestyle"><div className="category-label"><span className="eyebrow">Start exploring</span><strong>Find your kind of place</strong></div>{[["city-icon", "City living", "640 homes"], ["nature-icon", "Close to nature", "218 homes"], ["coast-icon", "By the water", "96 homes"], ["retreat-icon", "Weekend retreats", "184 homes"]].map(([icon, title, count]) => <a href="#listings" key={title}><span className={`category-icon ${icon}`}></span><span>{title}</span><small>{count}</small></a>)}</section>
      <section className="listing-section" id="listings"><div className="section-heading"><div><p className="eyebrow">Curated for you</p><h2>Homes that feel like home.</h2></div><a className="text-link" href="#listings">View all homes <span aria-hidden="true">&#8594;</span></a></div><div className="listing-grid">{visibleProperties.map((property) => <article className="property-card" key={property.id}><div className="property-image"><img src={property.image} alt={property.title} /><span className="property-tag">{property.tag}</span><button className={`save-button ${saved.includes(property.id) ? "is-saved" : ""}`} onClick={() => toggleSaved(property.id)} aria-label={`${saved.includes(property.id) ? "Remove" : "Save"} ${property.title}`}>{saved.includes(property.id) ? "Saved" : "Save"}</button></div><div className="property-info"><div><h3>{property.title}</h3><p>{property.location}</p></div><strong>{property.price}</strong></div><p className="property-details">{property.details}</p></article>)}</div>{!visibleProperties.length && <div className="empty-state">No {activeType.toLowerCase()} homes match that search yet. Try another place.</div>}</section>
      <section className="sell-banner" id="how-it-works"><div><p className="eyebrow">Your home has a story</p><h2>Ready to tell it well?</h2><p>List with Morrow and meet people looking for a place exactly like yours.</p></div><button className="dark-button" onClick={() => setShowListing(true)}>List your property <span aria-hidden="true">&#8599;</span></button></section>
    </main>
    <footer className="site-footer" id="guides"><div className="footer-brand"><a className="brand" href="#top"><span className="brand-mark">M</span><span>morrow</span></a><p>Thoughtful homes for<br />the way you want to live.</p></div><div><p className="footer-heading">Explore</p><a href="#listings">Buy a home</a><a href="#listings">Rent a home</a><a href="#listings">Neighborhoods</a></div><div><p className="footer-heading">For owners</p><button onClick={() => setShowListing(true)}>List your property</button><a href="#how-it-works">How it works</a><a href="#guides">Owner guides</a></div><div><p className="footer-heading">Stay in the know</p><p className="footer-small">A monthly note on good spaces and better living.</p><form className="email-form" onSubmit={(event) => { event.preventDefault(); setNotice("You are on the list. Welcome to Morrow."); }}><input type="email" placeholder="Your email address" aria-label="Your email address" required /><button aria-label="Subscribe">&#8594;</button></form></div><div className="footer-bottom"><span>© 2024 Morrow Homes</span><span>Made for living well.</span></div></footer>
    {notice && <div className="toast" role="status">{notice}</div>}
    {showListing && <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && setShowListing(false)}><div className="listing-modal" role="dialog" aria-modal="true" aria-labelledby="listing-title"><button className="close-button" onClick={() => setShowListing(false)} aria-label="Close listing form">&#10005;</button><p className="eyebrow">Sell with Morrow</p><h2 id="listing-title">Put your place<br /><em>in good company.</em></h2><p className="modal-copy">Tell us a little about your home and a member of our team will be in touch.</p><form onSubmit={handleListingSubmit}><label>Your name<input required placeholder="Jane Smith" /></label><label>Email address<input required type="email" placeholder="jane@example.com" /></label><label>Property location<input required placeholder="City, state" /></label><button className="dark-button" type="submit">Start my listing <span aria-hidden="true">&#8599;</span></button></form></div></div>}
  </div>;
}

const rootElement = document.getElementById("root");
if (rootElement) createRoot(rootElement).render(<App />);
